//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projectname
    {
        public int ProjectNameId { get; set; }
        public string ProjectName1 { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
