//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Resource
    {
        public int EmpId { get; set; }
        [Required]
        public string EmpName { get; set; }

        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string EmailId { get; set; }
        public Nullable<System.DateTime> YearOfPassing { get; set; }
        public DateTime DOJ { get; set; }
        public Nullable<int> CostCenter { get; set; }
        public string BU { get; set; }
        public string SBU { get; set; }
        public string ResourceType { get; set; }
        public string ClientReturn { get; set; }
        public string Project { get; set; }
        public string ProjectType { get; set; }
        public string ProjectName { get; set; }
        public string Aging { get; set; }
        public Nullable<System.DateTime> AgeBracket { get; set; }
        public string PerformanceAllowance { get; set; }
        public string LocationAllowance { get; set; }
        public string ReadyNessSatge { get; set; }
        public string StatusAsOfDate { get; set; }
    }
}
